web:
  build: .
  user: uid1000
  links:
   - db
  volumes:
#   - project:/opt/code
   - log:/log
  entrypoint: "python3 manage.py"
  command: "runserver 0.0.0.0:8000"
  ports:
   - "8123:8000"
  environment:
      PYTHONUNBUFFERED: 0
      DJANGO_SETTINGS_MODULE: project.settings.dev
db:
  image: postgres:9.3
